[package]
name = "allcookies-tracker-backend"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
refinery = { version= "0.7.0", features = ["tokio-postgres"] }
tokio = { version = "1.14.0", features = ["macros", "sync"] }
tokio-postgres = "0.7.5"