[package]
name = "allcookies-tracker-backend"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
actix-web = { version = "4.0.0-beta.13" }
async-trait="0.1"
bcrypt = "0.10"
ormx = { version = "0.10", features = ["postgres"] }

refinery = { version= "0.7", features = ["postgres"] }
serde="1"
serde_json="1"
sqlx = { version = "0.5",  features =  ["runtime-actix-native-tls", "postgres", "macros"] }