[package]
name = "allcookies-tracker-backend"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
actix-rt = "2"
actix-web = { version = "4.0.0-beta.13" }
async-trait = "0.1"
bcrypt = "0.10"
chrono = "0"
env_logger="0"
jwt = "0.15.0"
hmac = "0.11"
crypto-mac="0.11"
ormx = { version = "0.10", features = ["postgres"] }
sha2 = "0.9"
serde_json = "1"
serde = "1"
sqlx = { version = "0.5",  features =  ["runtime-actix-native-tls", "chrono", "postgres", "macros"] }