apiVersion: v1
kind: Service
metadata:
  name: allcookies-admin
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
      app: allcookies-admin
