apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: allcookies-tracker-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4096m
spec:
  tls:
    - hosts:
        - "{{ .Values.host }}"
      secretName: tls
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: allcookies-tracker-api
                port:
                  number: 80
