@server=http://localhost:8088
# @server=https://allcookies-tracker.a-dev.com

###
GET {{server}}/health

###
# @name auth
POST {{server}}/auth/sign-in
Content-Type: application/json

{
    "login": "seregat1984@gmail.com",
    "password": "123456"
}

###
GET {{server}}/profile/me
Authorization: {{auth.response.body.jwt}}

###
GET {{server}}/admin/selling-point/
Authorization: {{auth.response.body.jwt}}

###
GET {{server}}/client/selling-point
Authorization: {{auth.response.body.jwt}}

###
GET {{server}}/client/selling-point?lat=10.23&lon=30.99
Authorization: {{auth.response.body.jwt}}

###
POST {{server}}/admin/selling-point/
Authorization: {{auth.response.body.jwt}}
Content-Type: application/json

{
    "title": "A1234",
    "is_disabled": false
}

###
POST {{server}}/client/selling-point/
Authorization: {{auth.response.body.jwt}}
Content-Type: application/json

{
    "title": "Test point2-2233",
    "is_disabled": false,
    "location": {
        "lon": 50,
        "lat": 33
    }
}

###
PATCH {{server}}/admin/selling-point/7
Authorization: {{auth.response.body.jwt}}
Content-Type: application/json

{
    "title": "Барабашово"
}

###
PATCH {{server}}/admin/selling-point/3
Authorization: {{auth.response.body.jwt}}
Content-Type: application/json

{
    "title": "Test point3",
    "description": "Test desc",
    "address": "Loc 1 asdsd",
    "is_disabled": false,
    "location": {
        "lon": 20,
        "lat": 20
    }
}

###
DELETE {{server}}/admin/selling-point/3
Authorization: {{auth.response.body.jwt}}

###
GET {{server}}/admin/product/
Authorization: {{auth.response.body.jwt}}

###
GET {{server}}/client/product/
Authorization: {{auth.response.body.jwt}}


###
POST {{server}}/admin/product/
Authorization: {{auth.response.body.jwt}}
Content-Type: application/json

{
    "title": "Ежики",
    "is_disabled": false
}

###
PATCH {{server}}/admin/product/5
Authorization: {{auth.response.body.jwt}}
Content-Type: application/json

{
    "title": "Йижачкы",
    "is_disabled": false
}

###
DELETE {{server}}/admin/product/5
Authorization: {{auth.response.body.jwt}}

###
# @name user_accounts
GET {{server}}/admin/user-accounts
Authorization: {{auth.response.body.jwt}}

###
GET {{server}}/admin/user-accounts/{{user_accounts.response.body.$.data[0].id}}
Authorization: {{auth.response.body.jwt}}

###
POST {{server}}/admin/user-accounts/
Authorization: {{auth.response.body.jwt}}
Content-Type: application/json

{
    "login": "somebody@manager.com",
    "password": "test123",
    "name": "Alex Doe",
    "is_blocked": false
}

###
PATCH {{server}}/admin/user-accounts/4
Authorization: {{auth.response.body.jwt}}
Content-Type: application/json

{
    "password": "2233"
}
